- name: Disable all nodes swap memory
  hosts: nodes
  become: true
  tasks:
    #Step 1
    - name: Gather facts
      ansible.builtin.setup:

    - name: Disable swap
      ansible.builtin.command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Ensure swap is disabled in /etc/fstab
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^(.+\s+swap\s+.+)$'
        replace: '# \1'